<a href="https://colab.research.google.com/github/FreJa90/python_for_ds_tasks/blob/main/hw_10_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd
df = pd.read_csv('drive/MyDrive/Введення у Pandas/data/supermarket_sales.csv')

In [4]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [6]:
df.groupby('Branch')['Total'].sum().round(2)

Branch
A    106200.37
B    106197.67
C    110568.71
Name: Total, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [10]:
df.groupby(by = ['Branch', 'City'])['Total'].sum().round(2)

Branch  City
A       Yangon       106200.37
B       Mandalay     106197.67
C       Naypyitaw    110568.71
Name: Total, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [14]:
invoice_by_category = df.pivot_table(index = 'Branch', columns= 'Product line', values= 'Invoice ID', aggfunc = 'count')
invoice_by_category.head()

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [18]:
invoice_by_category['Electronic accessories'].agg(['max', 'idxmax'])

max       60
idxmax     A
Name: Electronic accessories, dtype: object

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

В якому філіалі магазину Branch найбільше купують товарів Health & Beauty, і хто(Gender)?

In [23]:
invoice_by_gender = df.pivot_table(index = ['Branch', 'Gender'], columns= 'Product line', values= 'Invoice ID', aggfunc = 'count')
invoice_by_gender['Health and beauty'].agg(['max', 'idxmax'])

max              33
idxmax    (B, Male)
Name: Health and beauty, dtype: object

In [25]:
invoice_by_gender.loc['B', 'Health and beauty']

Gender
Female    20
Male      33
Name: Health and beauty, dtype: int64

Цікаво, що в філіалі B здовров'ям та красою цікавляться більше чоловікі, можна розширити лінійки доглядової косметики, та різні добавки, протеїни

Перевіримо, а чи ці покупки прибуткові. Можливо чоловіки купують багато дешевих товарів, а жінки менше, але дорогих.

In [29]:
df[df['Product line'] == 'Health and beauty'].groupby(by = ['Gender','Branch','Product line'])['Total'].sum().round(2)

Gender  Branch  Product line
Female  A       Health and beauty     5714.90
        B       Health and beauty     6400.35
        C       Health and beauty     6445.74
Male    A       Health and beauty     6882.86
        B       Health and beauty    13580.31
        C       Health and beauty    10169.59
Name: Total, dtype: float64

Все ж таки в гілці B чоловікі абсолютні лідери і по кількості і по сумі чеку, можемо винагородити їх розширенням асортименту або ж подивитись найпопулярніші товари і влаштувати якусь акцію типу 2+1.

Який найпопулярніший спосіб оплати по філіям та містам, в залежності від статевої приналежності.

In [39]:
df.groupby(by=['Branch', 'City', 'Gender'])['Payment'].agg(lambda x: x.value_counts().idxmax())

Branch  City       Gender
A       Yangon     Female           Cash
                   Male          Ewallet
B       Mandalay   Female    Credit card
                   Male          Ewallet
C       Naypyitaw  Female           Cash
                   Male             Cash
Name: Payment, dtype: object

Бачимо що в двох філіях чоловікі викорисовують Ewallet, а жінки картки і cash. цікаво що філія C має найпопклярніший спосіб оплати готівковий, що цікаово для 21 сторіччя і треба перевірити чи не мають проблем там інші способи оплати.